// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591

namespace Popug.Billing.Api.Data
{
	[Table("billing_cycles")]
	public partial class BillingCycleEntity
	{
		[Column("billing_cycle_id"        , DataType = DataType.Int32         , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int            BillingCycleId        { get; set; } // integer
		[Column("account_id"              , DataType = DataType.Int32                                                                                           )] public int            AccountId             { get; set; } // integer
		[Column("close_at"                , DataType = DataType.DateTimeOffset                                                                                  )] public DateTimeOffset CloseAt               { get; set; } // timestamp (6) with time zone
		[Column("payment_operation_log_id", DataType = DataType.Int32                                                                                           )] public int?           PaymentOperationLogId { get; set; } // integer
	}
}
