// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Mapping;

#pragma warning disable 1573, 1591

namespace Popug.Billing.Api.Data
{
	[Table("tasks")]
	public partial class TaskEntity
	{
		[Column("task_id"        , DataType = DataType.Int32  , IsPrimaryKey = true)] public int     TaskId         { get; set; } // integer
		[Column("description"    , DataType = DataType.Text                        )] public string  Description    { get; set; } // text
		[Column("assign_charge"  , DataType = DataType.Decimal                     )] public decimal AssignCharge   { get; set; } // numeric(14,4)
		[Column("complete_charge", DataType = DataType.Decimal                     )] public decimal CompleteCharge { get; set; } // numeric(14,4)
	}
}
