// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Mapping;

#pragma warning disable 1573, 1591

namespace Popug.Tasks.Api.Data
{
	[Table("popug")]
	public partial class PopugEntity
	{
		[Column("user_id"  , CanBeNull = false, DataType = DataType.Text, IsPrimaryKey = true)] public string UserId   { get; set; } // text
		[Column("user_name", CanBeNull = false, DataType = DataType.Text                     )] public string UserName { get; set; } // text
		[Column("user_role", CanBeNull = false, DataType = DataType.Text                     )] public string UserRole { get; set; } // text
	}
}
