version: '3.4'

networks:
  infrastructure:
    name: kav-async-arch_default
    external: true

services:
  popug.tasks.api:
    image: ${DOCKER_REGISTRY-}popugtaskapi
    build:
      context: .
      dockerfile: Popug.Task.Api/Dockerfile
    networks:
        - infrastructure

  popug.billing.api:
    image: ${DOCKER_REGISTRY-}popugbillingapi
    build:
      context: .
      dockerfile: Popug.Billing.Api/Dockerfile
    networks:
        - infrastructure


  popug.analytic.api:
    image: ${DOCKER_REGISTRY-}popuganalyticapi
    build:
      context: .
      dockerfile: Popug.Analytic.Api/Dockerfile
    networks:
        - infrastructure

